LOG=1; # OR LOG=0;
SINGBOX_EXTENDED=1;
RESTART_AFTER_UPDATE=1;
AUTOUPDATE_INTERVAL=3600;
SUBSCRIPTION_URL=;
INBOUNDS_CONFIG_URL=;
EXTERNAL_UI_SECRET=;
#TPROXY_INTERFACE="eth0";

###################

#(( $SINGBOX_EXTENDED )) && SUBSCRIPTION_URL_PATH="/json";
RESTART_AFTER_UPDATE="${RESTART_AFTER_UPDATE:-1}";
AUTOUPDATE_INTERVAL="${AUTOUPDATE_INTERVAL:-0}";
SUBSCRIPTION_URL="${SUBSCRIPTION_URL:-}";
SUBSCRIPTION_URL_PATH="${SUBSCRIPTION_URL_PATH:-/singbox}";
EXTERNAL_UI_DOWNLOAD_URL="${EXTERNAL_UI_DOWNLOAD_URL:-}";
EXTERNAL_UI_SECRET="${EXTERNAL_UI_SECRET:-}";
CONFIG_DIR="${CONFIG_DIR:-/etc/sing-box/config}";
TMP_DIR="${TMP_DIR:-/tmp/singbox-tproxy}";
CONFIG_FILE="${CONFIG_FILE:-config.json}";
LOCAL_INBOUNDS_CONFIG="${TMP_DIR}/inbounds.json";
FINAL_CONFIG_FILE="${CONFIG_DIR}/${CONFIG_FILE}";
